id: 3f32660be6524ecfb3e74ba7481be29d
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_300-The_Sutra_on_Reliance_upon_a_Virtuous_Spiritual_Friend-v1
  language: en
  author: ''
  volume: {}
